### PR TITLE
fix utf8 inconsistencies

### PR DESCRIPTION
**Pull request by kergma**
There are some inconsistencies in pg_enable_utf8 behaviour, described in cpan bugs page 
https://rt.cpan.org/Public/Bug/Display.html?id=103137

this will fix them

### CODE REVIEW

**Comment by nwellnhof** [comment]
Why isn't this fixed in over a year? This is a serious issue for legacy setups with `pg_enable_utf8=>0`.

**Comment by machack666** [comment]
I am reviewing this patch now and will merge if everything passes.

**Comment by machack666** [comment]
This has caused failing tests with some of the test data in t/30unicode.t.  I will investigate further and see if I can find out why and if it's to do with this patch or if it was already failing.

**Comment by machack666** [comment]
Yeah, it's definitely the patch causing the failures.  I'll see what I can come up with, or if the original author want to take a look at this with the latest implementation that'd be great.

**Comment by machack666** [comment]
@kergma ^^^

**Comment by machack666** [comment]
After some analysis, we've concluded the test that is failing is bad.  I'm working on getting a better test given the patch here and we'll get this committed.

**Pull request merged**
